# Generated by Django 5.2.3 on 2025-06-28 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emenda',
            fields=[
                ('cod_emenda', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('cod_funcao', models.IntegerField(primary_key=True, serialize=False)),
                ('subfuncao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id_local', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Proponente',
            fields=[
                ('cod_proponente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AcaoOrcamentaria',
            fields=[
                ('cod_acao', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
                ('codigo_emenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emendas_app.emenda')),
            ],
        ),
        migrations.AddField(
            model_name='emenda',
            name='codigo_funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emendas_app.funcao'),
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('cod_instituicao', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emendas_app.localidade')),
            ],
        ),
        migrations.AddField(
            model_name='emenda',
            name='codigo_proponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emendas_app.proponente'),
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_emenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emendas_app.emenda')),
                ('codigo_instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emendas_app.instituicao')),
            ],
            options={
                'unique_together': {('codigo_emenda', 'codigo_instituicao')},
            },
        ),
    ]
