# Generated by Django 5.2.3 on 2025-06-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emendas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcao',
            old_name='subfuncao',
            new_name='nome',
        ),
    ]
