# Generated by Django 5.2.3 on 2025-06-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendas_app', '0002_rename_subfuncao_funcao_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidade',
            name='id_local',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
