# Generated by Django 5.2.3 on 2025-06-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emendas_app', '0003_alter_localidade_id_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidade',
            name='nome',
        ),
    ]
