# Generated by Django 5.2.3 on 2025-06-29 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendas_app', '0004_remove_localidade_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('cod_programa', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='acaoorcamentaria',
            name='valor_empenhado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='acaoorcamentaria',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='emenda',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emenda',
            name='numero_emenda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='acaoorcamentaria',
            name='codigo_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emendas_app.programa'),
        ),
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_convenio', models.BooleanField(blank=True, null=True)),
                ('codigo_emenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emendas_app.emenda')),
                ('codigo_instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emendas_app.instituicao')),
            ],
            options={
                'unique_together': {('codigo_emenda', 'codigo_instituicao')},
            },
        ),
        migrations.DeleteModel(
            name='Beneficio',
        ),
    ]
